#Config 1.0 for PowerlessLampsRedux plugin by:
#moikheck
#Golem_Leader
#Meadow Heckman
#(All of the above are the same person)

#Determines whether permissions are used for the plugin
#Permission Names:
#lamp.toggle
use-permissions: true